import "./globals.css";
import { Metadata } from "next";
import { GeistSans } from "geist/font/sans";
import { GeistMono } from "geist/font/mono";
import { ThemeWrapper } from "@/components/atoms/theme-wrapper";
import { ResponsiveIndicator } from "@/components/atoms/responsive-indicator";
import {
  NavbarMobile,
  NavbarProvider,
} from "@/components/organisms/navbar-mobile";
import { Navbar } from "@/components/organisms/navbar/navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="es" suppressHydrationWarning>
      <body className={`${GeistSans.variable} ${GeistMono.variable} font-mono`}>
        <ThemeWrapper
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <main>
            <NavbarProvider>
              <Navbar />
              {/* <NavbarMobile /> */}
            </NavbarProvider>
            {children}
          </main>
        </ThemeWrapper>
        <ResponsiveIndicator />
      </body>
    </html>
  );
}
